server:
  port: 8083

spring:
  application:
    name: imogestion
  main:
    allow-bean-definition-overriding: true

  devtools:
    add-properties: 'false'
    livereload:
      enabled: 'true'

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    password: imogestion
    username: imogestion
    url: jdbc:postgresql://localhost:5432/imogestion

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      driver-class-name: org.postgresql.Driver
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      connection:
        release_mode: after_transaction
        provider_disables_autocommit: true

  flyway:
    enabled: 'true'
    locations: classpath:db/migration
    validate-migration-naming: 'true'
